[package]
name = "pqsecure-mesh"
version = "0.1.0"
edition = "2021"
authors = ["Jerry <vp780412@gmail.com>"]
description = "Post-Quantum Secure Proxy for Microservices"
readme = "README.md"
license = "BSL-1.1"
repository = "https://github.com/JerryR7/pqsecure-mesh"

[dependencies]
# Asynchronous runtime
tokio = { version = "1.29", features = ["full"] }

# Web framework
axum = { version = "0.6", features = ["headers"] }
tower = { version = "0.4", features = ["timeout"] }
tower-http = { version = "0.4", features = ["trace", "cors", "compression-full"] }

# gRPC support
tonic = "0.9"
prost = "0.11"

# Serialization/Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

# Configuration management
config = "0.13"
dotenvy = "0.15"

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# HTTP/2 support
h2 = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
tracing-opentelemetry = "0.19"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Cryptography (requires actual post-quantum cryptography libraries)
rustls = "0.21"
rustls-pemfile = "1.0"
rcgen = "0.10"
tokio-rustls = "0.24"
rand = "0.8"
md5 = "0.7"
base64 = "0.21"

# Distributed tracing
opentelemetry = { version = "0.19", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.19", features = ["rt-tokio"] }

# Monitoring
prometheus = "0.13"

# Other utilities
async-trait = "0.1"
bytes = "1.4"
once_cell = "1.17"
uuid = { version = "1.3", features = ["v4", "serde"] }
url = "2.3"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.11"

[build-dependencies]
tonic-build = "0.9"