[package]
name = "pqsecure-mesh"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Post-Quantum Secure Proxy for Microservices"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/your-username/pqsecure-mesh"

[dependencies]
# 非同步運行時
tokio = { version = "1.29", features = ["full"] }

# Web 框架
axum = { version = "0.6", features = ["headers"] }
tower = { version = "0.4", features = ["timeout"] }
tower-http = { version = "0.4", features = ["trace", "cors", "compression-full"] }

# gRPC 支援
tonic = "0.9"
prost = "0.11"

# 序列化/反序列化
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# 配置管理
config = "0.13"
dotenvy = "0.15"

# HTTP 客戶端
reqwest = { version = "0.11", features = ["json"] }

# 日誌
tracing = "0.1"
tracing-subscriber = "0.3"

# 錯誤處理
thiserror = "1.0"
anyhow = "1.0"

# 密碼學（這裡需要加入實際的後量子加密庫）
rustls = "0.21"
rcgen = "0.10"
rand = "0.8"

# 其他工具
async-trait = "0.1"
bytes = "1.4"
once_cell = "1.17"
uuid = { version = "1.3", features = ["v4", "serde"] }

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.11"

[build-dependencies]
tonic-build = "0.9"