version: "3.8"

services:
  # Smallstep CA service
  step-ca:
    image: smallstep/step-ca:latest
    container_name: step-ca
    volumes:
      - ./step:/home/step
    ports:
      - "9000:9000"
    environment:
      - DOCKER_STEPCA_INIT_NAME=PQSecure Mesh CA
      - DOCKER_STEPCA_INIT_DNS=localhost
      - DOCKER_STEPCA_INIT_ADDRESS=:9000
      - DOCKER_STEPCA_INIT_PROVISIONER=pqsecure-admin
      - DOCKER_STEPCA_INIT_PASSWORD=123456
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-check-certificate", "-O", "-", "https://127.0.0.1:9000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Backend API service (simulating EDR manager)
  backend:
    image: nginx:alpine
    container_name: pqsecure-backend
    volumes:
      - ./sample/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./sample/html:/usr/share/nginx/html
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://127.0.0.1:8080"]
      interval: 10s
      timeout: 5s
      retries: 3

  # PQSecure Mesh proxy
  pqsecure-mesh:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pqsecure-mesh
    volumes:
      - ./config:/app/config
      - ./certs:/app/certs
    environment:
      - RUST_LOG=info
      - PQSECURE_CA_API_URL=https://step-ca:9000
      - PQSECURE_BACKEND_ADDR=backend:8080
      - PQSECURE_CA_TOKEN=${SMALLSTEP_TOKEN:-default-testing-token}
    ports:
      - "8443:8443"
    depends_on:
      step-ca:
        condition: service_healthy
      backend:
        condition: service_healthy
    restart: unless-stopped