# Default policy configuration
id: default
allow_from:
  # Allow all services within the same tenant
  - id: "spiffe://default/*"
  # Allow connections from the monitoring system
  - id: "spiffe://default/monitoring"
  # Allow connections from the controller
  - id: "spiffe://default/controller"

allow_methods:
  # Allow HTTP methods
  - ["GET", "/health"]
  - ["GET", "/metrics"]
  - ["GET", "/api/v1/*"]
  - ["POST", "/api/v1/*"]
  # Allow gRPC methods
  - "service.*"

# Deny rules
deny_rules:
  # Deny requests from specific subnets
  - ip: "10.0.0.0/8"
  # Deny specific methods and paths
  - method: "DELETE"
    path: "/api/v1/critical/*"
  # Deny requests outside of working hours
  - start_hour: 22
    end_hour: 6