# PQSecure Mesh 默認配置

[general]
app_name = "PQSecure Mesh"
log_level = "info"
data_dir = "./data"

[api]
listen_addr = "0.0.0.0"
listen_port = 8080
path_prefix = "/api/v1"
enable_http2 = true

[proxy]
listen_addr = "0.0.0.0"
listen_port = 9090
upstream_addr = "127.0.0.1"
upstream_port = 8000
enable_grpc = true
enable_http = true
idle_timeout_seconds = 300

[cert]
enable_mtls = true
enable_pqc = true
ca_type = "mock"  # "smallstep" 或 "mock"
# smallstep_url = "https://ca.example.com"
# smallstep_token = "your-bootstrap-token"
certs_dir = "./data/certs"
cert_duration_hours = 8760  # 1 年
cert_renew_threshold_pct = 20